### ISSUE TITLE
deleting a team that has players leaves players with a null teamid in the db - is this ok?

### ISSUE THREAD

**Issue by neilfr** [neilfr/scorekeeper#19]

**Comment by chrisfernandes123** [comment]
This makes sense as players may not be assigned to a team.  I'm guessing we would need a way to update the team ID for an existing player. I'm not sure if this is MVP though. We could just assume that no teams are deleted and every player needs a team assigned upon player creation.

**Comment by neilfr** [comment]
agreed... let's leave it as is
