### ISSUE TITLE
fix local storage of game time to be per game

### ISSUE THREAD

**Issue by chrisfernandes123** [neilfr/scorekeeper#48]
I went into game 1, started the clock and then stopped the click. I exited game 1 and went into game 2.  In game 2 it showed the clock as of the game 1 time.  Maybe used an object to store the game time where the game id is specified along with the clock time.

**Comment by neilfr** [comment]
For now, I've just got the clock resetting each time the scorekeeper picks a game.  It'll get us through the demo for now.  That said, I'm thinking that once a scorekeeper starts a game, (s)he wouldn't leave it and then come back to it at a later point in time expecting the clock time to be preserved... games are usually played until done.  That said, let me know if I'm missing a scenario you have in mind.  I'll leave this open for now until we talk it through.

**Comment by chrisfernandes123** [comment]
Okay sounds good.  I agree with your explanation of the scenario.  I will close this issue.
