### ISSUE TITLE
game appear multiple times in the view games lists of gameselect

### ISSUE THREAD

**Issue by neilfr** [neilfr/scorekeeper#72]

**Comment by chrisfernandes123** [comment]
Completed.  The same class ".scores-appear-here" was used 4 times for 4 different divs.  I changed the code to make 4 unique class names:

".scores-appear-here-view-all-games"
".scores-appear-here-view-todays-games"
".scores-appear-here-view-past-games"
".scores-appear-here-view-future-games"
