### ISSUE TITLE
gameselect screen - all goals show invalid date for the goal scored time

### ISSUE THREAD

**Issue by neilfr** [neilfr/scorekeeper#73]

**Comment by chrisfernandes123** [comment]
@neilfr Is this resolved already?  I can't reproduce this error based on the current pull from Test.

**Comment by chrisfernandes123** [comment]
Completed.  I created a function called formatGoalTime in the gameselect.html javascript section.  The function formatGoalTime takes the timeRemaining as a parameter and uses Neil's logic from scorekeeper.js to derive the minutes, seconds, an 10th seconds.  The function formatGoalTime returns a string that looks like 04:57:2.
